export const currentStock = [
    {
      productName: "Laptop",
      Category: "Electronics",
      Description: "High-performance laptop with a sleek design.",
      Price: 1000,
      quantity: 50,
      notes: "Comes in various colors.",
    },
    {
      productName: "Smartphone",
      Category: "Electronics",
      Description: "Feature-rich smartphone with a powerful camera.",
      Price: 800,
      quantity: 100,
      notes: "Supports 5G connectivity.",
    },
    {
      productName: "Headphones",
      Category: "Electronics",
      Description: "Wireless headphones with noise-cancellation.",
      Price: 150,
      quantity: 200,
      notes: "Long battery life.",
    },
    {
      productName: "Running Shoes",
      Category: "Sports",
      Description: "Comfortable running shoes for athletes.",
      Price: 80,
      quantity: 75,
      notes: "Available in various sizes.",
    },
    {
      productName: "Dress Shirt",
      Category: "Fashion",
      Description: "Formal dress shirt made of high-quality fabric.",
      Price: 50,
      quantity: 120,
      notes: "Slim-fit design.",
    },
    {
      productName: "Coffee Maker",
      Category: "Appliances",
      Description: "Automatic coffee maker for home use.",
      Price: 120,
      quantity: 30,
      notes: "Brews up to 10 cups at once.",
    },
    {
      productName: "Backpack",
      Category: "Accessories",
      Description: "Stylish and spacious backpack for daily use.",
      Price: 70,
      quantity: 50,
      notes: "Water-resistant material.",
    },
    {
      productName: "Yoga Mat",
      Category: "Sports",
      Description: "Non-slip yoga mat for practicing yoga.",
      Price: 25,
      quantity: 100,
      notes: "Eco-friendly material.",
    },
    {
      productName: "Bluetooth Speaker",
      Category: "Electronics",
      Description: "Portable Bluetooth speaker with excellent sound quality.",
      Price: 60,
      quantity: 80,
      notes: "Built-in microphone for hands-free calls.",
    },
    {
      productName: "Gaming Mouse",
      Category: "Gaming",
      Description: "High-precision gaming mouse with customizable buttons.",
      Price: 40,
      quantity: 60,
      notes: "RGB lighting effects.",
    },
  ];
  